spring:
  datasource:
    master:
      jdbc-url: jdbc:mariadb://192.0.2.115:3306/def
      driver-class-name: org.mariadb.jdbc.Driver
      username: kjy
      password: qwer1234
    slave:
      jdbc-url: jdbc:mariadb://192.0.2.116:3306/def
      driver-class-name: org.mariadb.jdbc.Driver
      username: slavekjy
      password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
