spring:
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      jdbc-url: ${MASTER_JDBC_URL}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${MASTER_DB_USERNAME}
      password: ${MASTER_DB_PASSWORD}
    slave:
      jdbc-url: ${SLAVE_JDBC_URL}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${SLAVE_DB_USERNAME}
      password: ${SLAVE_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret: ${JWT_SECRET}
  expired: 1800000